services:
  db:
    container_name: fast-api-postgres-db
    restart: always
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fast_api_postgres_db
      POSTGRES_PASSWORD: secure-password
      POSTGRES_USER: fast-api-postgres-user

  adminer:
    container_name: fast-api-postgres-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
